info:
  version: 1.0.0
<<<<<<< HEAD:product2_1.0.0.yaml
  title: Product2
  name: product2
=======
  title: Product11
  name: product11
>>>>>>> commitmernt:product11_1.0.0.yaml
gateways:
  - datapower-api-gateway
plans:
  default-plan:
    title: Default Plan
    description: Default Plan
    rate-limits:
      default:
        value: 100/1hour
    apis:
<<<<<<< HEAD:product2_1.0.0.yaml
      api21.0.0: {}
apis:
  api21.0.0:
    $ref: ./api2_1.0.0.yaml
=======
      api111.0.0: {}
apis:
  api111.0.0:
    $ref: ./api11_1.0.0.yaml
>>>>>>> commitmernt:product11_1.0.0.yaml
visibility:
  view:
    type: public
    orgs: []
    tags: []
    enabled: true
  subscribe:
    type: authenticated
    orgs: []
    tags: []
    enabled: true
product: 1.0.0
